name: CI
'on':
  push:
    branches: 
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure nodejs
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name: Install dependencias
      run: yarn 

    - name: Copy to server
      uses: appleboy/scp-action@master
      with:
        host: '${{ secrets.SSH_HOST }}'
        username: '${{ secrets.SSH_USER }}'
        port: '${{ secrets.SSH_PORT }}'
        key: ${{ secrets.SSH_KEY }}
        source: '*'
        target: '/home/ubuntu/deploy'

    - name: Execute pm2 Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: pm2 restart 0 
